version: '2'
services:
  calcite-sql:
    container_name: calcite-sql
    build:
      context: ./sql
      dockerfile: Dockerfile.server
    image: calcite-sql:latest
    ports: # HOST_PORT:CONTAINER_PORT
    - 80:8080  # application
    networks:
    - spring-cloud-network
    volumes:
    - calcite-sql:/var/lib/app/config
    logging:
      driver: json-file
networks:
  spring-cloud-network:
    driver: bridge
volumes:
  calcite-sql:
    external: true