#version: '2'
version: '3.3'

services:
  calcite-sql:
    container_name: calcite-sql
    build:
      context: ./sql
      dockerfile: Dockerfile.server
    image: calcite-sql:latest
    depends_on:
    - mysql
    ports: # HOST_PORT:CONTAINER_PORT
    - 80:8080  # application
    networks:
    - spring-cloud-network
    volumes:
    - calcite-sql:/var/lib/app/config
    logging:
      driver: json-file
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
    - mysql/env.list
    volumes:
    - type: bind # data storage
      source: ./mysql/db/data/
      target: /var/lib/mysql/
    - type: bind # init database
      source: ./mysql/db/init/
      target: /docker-entrypoint-initdb.d/
    ports:
    - 3306:3306
networks:
  spring-cloud-network:
    driver: bridge
volumes:
  calcite-sql:
    external: true