#version: '2'
version: '3.3'

services:
  calcite-core:
    container_name: calcite-core
    build:
      context: ./core
      dockerfile: Dockerfile.server
    image: calcite-core:latest
    depends_on:
    - mysql
    ports: # HOST_PORT:CONTAINER_PORT
    - 80:8080  # application
    networks:
    - spring-cloud-network
    links:
    - mysql:mysql
    - postgres:postgres
    volumes:
    - calcite-core:/var/lib/app/config
    logging:
      driver: json-file
  mysql:
    container_name: mysql
    image: mysql:latest
    env_file:
    - mysql/env.list
    volumes:
#     - type: bind # data storage
#       source: ./mysql/db/data/
#       target: /var/lib/mysql/
    - type: bind # init database
      source: ./mysql/db/init/
      target: /docker-entrypoint-initdb.d/
    ports:
    - 3306:3306
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file:
    - postgres/env.list
    volumes:
#     - type: bind # data storage
#       source: ./postgres/db/data/
#       target: /var/lib/postgresql/data
    - type: bind # init database
      source: ./postgres/db/init/
      target: /docker-entrypoint-initdb.d/
    ports:
    - 5432:5432
networks:
  spring-cloud-network:
    driver: bridge
volumes:
  # docker volume create --name=calcite-core
  calcite-core:
    external: true